version: "3.8"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'shopware'
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
            MYSQL_DATABASE: shopware
        ports:
          - "3306:3306"
        volumes:
          - tmp2-mysql-data:/var/lib/mysql
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - tmp2-redis_data:/data

    init-perm:
        image: alpine
        volumes:
            - tmp2-files:/var/www/html/files
            - tmp2-theme:/var/www/html/public/theme
            - tmp2-media:/var/www/html/public/media
            - tmp2-thumbnail:/var/www/html/public/thumbnail
            - tmp2-sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

    init:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file: .env.docker
        entrypoint: /setup
        volumes:
            - tmp2-files:/var/www/html/files
            - tmp2-theme:/var/www/html/public/theme
            - tmp2-media:/var/www/html/public/media
            - tmp2-thumbnail:/var/www/html/public/thumbnail
            - tmp2-sitemap:/var/www/html/public/sitemap
        depends_on:
            db:
                condition: service_started
            init-perm:
                condition: service_completed_successfully
    web:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - tmp2-files:/var/www/html/files
            - tmp2-theme:/var/www/html/public/theme
            - tmp2-media:/var/www/html/public/media
            - tmp2-thumbnail:/var/www/html/public/thumbnail
            - tmp2-sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .env.docker
        ports:
            - 8082:8000

    worker:
        image: local
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - tmp2-files:/var/www/html/files
            - tmp2-theme:/var/www/html/public/theme
            - tmp2-media:/var/www/html/public/media
            - tmp2-thumbnail:/var/www/html/public/thumbnail
            - tmp2-sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .env.docker
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=300", "--memory-limit=512M" ]
        deploy:
            replicas: 3

volumes:
    tmp2-mysql-data:
    tmp2-files:
    tmp2-theme:
    tmp2-media:
    tmp2-thumbnail:
    tmp2-sitemap:
    tmp2-redis_data: